runtime: java17  # Spécifie que tu utilises Java 17

env: flex  # Utilisation de l'environnement flexible pour un contrôle plus précis

entrypoint: java -jar centre-api/target/centre-api.jar  # Commande pour démarrer ton application backend

instance_class: F2  # Configure la classe de l'instance pour les performances

env_variables:
  SPRING_PROFILES_ACTIVE: "prod"  # Exemple d'une variable d'environnement, à ajuster selon ton application
