services:
  - type: web
    name: centre-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: centre-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: centre-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: centre-db
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

databases:
  - name: centre-db
    plan: free
    postgresMajorVersion: 15
