/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppToaster: typeof import('./components/AppToaster.vue')['default']
    DsfrAccordion: typeof import('@gouvminint/vue-dsfr')['DsfrAccordion']
    DsfrAccordionItem: typeof import('@gouvminint/vue-dsfr')['DsfrAccordionItem']
    DsfrAccordionsGroup: typeof import('@gouvminint/vue-dsfr')['DsfrAccordionsGroup']
    DsfrAlert: typeof import('@gouvminint/vue-dsfr')['DsfrAlert']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    DsfrButtonGroup: typeof import('@gouvminint/vue-dsfr')['DsfrButtonGroup']
    DsfrHeader: typeof import('@gouvminint/vue-dsfr')['DsfrHeader']
    DsfrNavigation: typeof import('@gouvminint/vue-dsfr')['DsfrNavigation']
    DsfrNavigationMegaMenu: typeof import('@gouvminint/vue-dsfr')['DsfrNavigationMegaMenu']
    DsfrTabContent: typeof import('@gouvminint/vue-dsfr')['DsfrTabContent']
    DsfrTabItem: typeof import('@gouvminint/vue-dsfr')['DsfrTabItem']
    DsfrTabs: typeof import('@gouvminint/vue-dsfr')['DsfrTabs']
    DsfrTile: typeof import('@gouvminint/vue-dsfr')['DsfrTile']
    DsfrTiles: typeof import('@gouvminint/vue-dsfr')['DsfrTiles']
    ReloadPrompt: typeof import('./components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
