/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppToaster: typeof import('./components/AppToaster.vue')['default']
    DsfrAlert: typeof import('@gouvminint/vue-dsfr')['DsfrAlert']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    DsfrButtonGroup: typeof import('@gouvminint/vue-dsfr')['DsfrButtonGroup']
    DsfrCol: typeof import('@gouvminint/vue-dsfr')['DsfrCol']
    DsfrContainer: typeof import('@gouvminint/vue-dsfr')['DsfrContainer']
    DsfrHeader: typeof import('@gouvminint/vue-dsfr')['DsfrHeader']
    DsfrRow: typeof import('@gouvminint/vue-dsfr')['DsfrRow']
    DsfrTabContent: typeof import('@gouvminint/vue-dsfr')['DsfrTabContent']
    DsfrTabItem: typeof import('@gouvminint/vue-dsfr')['DsfrTabItem']
    DsfrTabs: typeof import('@gouvminint/vue-dsfr')['DsfrTabs']
    DsfrTile: typeof import('@gouvminint/vue-dsfr')['DsfrTile']
    ReloadPrompt: typeof import('./components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
